### ISSUE TITLE
Land allocation error running GCAM v4.4 on a cluster

### ISSUE THREAD

**Issue by zcranmer** [JGCRI/gcam-core#40] opened 2018-07-10 10:03 UTC
We have installed GCAM v4.4 on a unix cluster and when we try to run it we get the following error in Period 1/1990:  The sum of land areas in region USA exceeds the land allocation by -8942.4 (-100%) in period 1.

In the land_input_1.xml file, the USA land allocation appears to be set to 8942.4 in 1975 with fillout=1.

What could be causing this error?  Thanks for any help you can provide.

**Comment by kvcalvin** [comment] 2018-07-10 12:44
Could you upload your `main_log.txt`?

**Comment by zcranmer** [comment] 2018-07-10 14:45
[main_log.txt](https://github.com/JGCRI/gcam-core/files/2180849/main_log.txt)

**Comment by flannerydolan** [comment] 2018-07-11 13:53
HI all, I also got this error while running GCAM v4.4

**Comment by pralitp** [comment] 2018-07-11 18:21
I have now been able to replicate this bug by switching to GCC 7.  I have not yet worked out what is going wrong.

Perhaps in the meantime you can try switching compilers.  We have had success with gcc 5.2 and  6.1 as well as LLVM/clang and Intel if any of those compilers are readily available to you.

**Comment by pralitp** [comment] 2018-07-25 21:12
Note, this is a duplicate of #36.

**Closed by pralitp** 2018-07-25 21:12 UTC
